version: '1.0.{build}'
image: ubuntu
branches:
  only:
  - master
install:
  # Install repo specific stuff here

before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet tool install -g Cake.Tool
  - cmd: dotnet cake build.cake
deploy: off