version: '1.0.{build}'
image: ubuntu
branches:
  only:
  - master
services:
- docker
install:
  # Install repo specific stuff here

before_build:
  -  dotnet --version
build_script:
  -  dotnet tool install -g Cake.Tool
  -  dotnet cake build.cake
deploy: off