dist: xenial
sudo: required
language: csharp
mono: none
dotnet: 5.0.101
solution: AspNetCoreDevOps.sln
services:
  - docker
script:
  - dotnet run  --project ./build/_build.csproj -GitHubAccessToken $GITHUB_ACCESS_TOKEN