sudo: required
language: csharp
solution: AspNetCoreDevOps.sln
dotnet: 3.0-sdk
addons:
  apt:
    packages:
    - sshpass
services:
  - docker
before_install:
  - docker-compose up -d --build
script:
  - dotnet restore
  - dotnet build
  - cd test/AspNetCoreDevOps.Controllers.Tests
  - dotnet test
  - cd ..
  - cd ..
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  - docker login $DOCKER_USER.azurecr.io -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER.azurecr.io/travisci
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
#deploy:
   #provider: script
   #script: bash deploy.sh
