pool:
   vmImage: 'Ubuntu 18.04'   
variables:
   buildConfiguration: 'Release' 
steps:
  - task: DotNetCoreInstaller@0
    inputs:
       version: '3.1.101' # replace this value with the version that you need for your project
  - script: |
        dotnet run  --project ./build/_build.csproj -GitHubAccessToken $(GithubAccessToken)
