trigger:
- master
jobs:
- job: Linux
  pool:
     vmImage: 'Ubuntu 16.04'   
     variables:
     buildConfiguration: 'Release' 
  steps:
  - script: |
       apt-get install sshpass
       docker-compose up -d --build
       dotnet restore
       dotnet build
       cd test/TravicCI.Controllers.Tests
       dotnet test
       cd ..
       cd ..
       docker login  $(dockerId).azurecr.io -u  $(dockerId) -p $(dockerPassword)
       docker build -f dockerfile -t $(dockerId).azurecr.io/$(Build.BuildId) .
       docker push $(dockerId).azurecr.io/$(Build.BuildId)
       bash deploy.azure-pipelines.sh
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: dotnet build
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet build
